# Generated by Django 4.1.7 on 2023-03-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_studentname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentName',
            field=models.CharField(max_length=100),
        ),
    ]
