# Generated by Django 4.1.7 on 2023-03-04 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_studentname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='studentEmail',
        ),
    ]
